// <auto-generated />
using FirstMvc.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstMvc.Migrations
{
    [DbContext(typeof(AppDbContexts))]
    [Migration("20230524072521_one")]
    partial class one
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FirstMvc.Models.Talaba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ismi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manzili")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Yoshi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Talabas");
                });
#pragma warning restore 612, 618
        }
    }
}
